//line lexer.go:2
//line lexer.l:33
package gyp

import (
    "fmt"
    "io"
    "log"
    "os"
    "math"
    "strconv"
    "strings"
    proto "github.com/golang/protobuf/proto"

    "github.com/VirusTotal/gyp/ast"
    "github.com/VirusTotal/gyp/hex"
    "github.com/VirusTotal/gyp/error"
)

// Necessary types for flexgo
type YYtype interface{}

// Note that the parser is generated with the yr prefix to avoid name
// collisions with the hex and regexp parsers.
type YYcontext struct {
  lval *yrSymType
}

// The YY_USER_DATA macro is used to define variables inside the Scanner
// Lex() method. These variables manage buffers for gathering groups of
// tokens. Flex collects tokens individually but strings and conditions may
// contain several tokens.
// Two different buffers are necessary because conditions may contain strings.

// This comment applies to the YY_USER_ACTION macro, which is having
// a problem with comments...
// For condition, the colons and whitespace will be collected in the
// prefix and the right brace for the suffix. Use strings.TrimLeft/Right



//line lexer.go:43

// START OF SKELL ------------------------------------------------------
// A lexical scanner generated by flexgo

type Scanner struct {
	In   io.Reader
	Out  io.Writer
	Lineno int

	Filename      string
	Wrap          func(*Scanner) bool
	IsInteractive func(io.Reader) bool
	Context       YYcontext

	lastAcceptingState   int
	lastAcceptingCpos    int
	debug                bool
	start                int
	stateBuf             []int
	statePtr             int
	fullState            int
	fullMatch            int
	fullLp               int
	lp                   int
	lookingForTrailBegin int
	holdChar             byte
	cBufP                int
	didBufferSwitchOnEof bool
	textPtr              int
	nChars               int
	init                 bool
	moreFlag             bool
    moreLen              int

	// buffer
	inputFile    io.Reader
	chBuf        []byte // input buffer
	bufPos       int    // current position in input buffer
	bufSize      int
	bufNChars    int
	Interactive  bool
	atBol        int // 0 (false) or 1 (true)
	fillBuffer   bool
	bufferStatus int
}

func NewScanner() *Scanner {
	yy := Scanner{
		Lineno: 1,
		In:            os.Stdin,
		Out:           os.Stdout,
		Wrap:          func(yyy *Scanner) bool { return true },
		IsInteractive: func(file io.Reader) bool { return yyInteractiveDefault },
		bufSize:       yyBufSize,
		chBuf:         make([]byte, yyBufSize+2),
		start:         1,
		stateBuf:      make([]int, yyBufSize+2),
		atBol:         1,
		debug:         yyFlexDebug,
		fillBuffer:    true,
	}
	return &yy
}

func (yy *Scanner) NewFile() {
	yy.Restart(yy.In)
}

const yyEndOfBufferChar = 0

const yyBufSize = 32768

const (
	eobActEndOfFile    = 0
	eobActContinueScan = 1
	eobActLastMatch    = 2
)

const (
	yyBufferNew        = 0
	yyBufferNormal     = 1
	yyBufferEofPending = 2
)

// [1.0] the user's section 1 definitions and yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here
/* Begin user sect3 */
const yyFlexDebug = false

const yyInteractiveDefault = false
// SKEL ----------------------------------------------------------------

// [1.5] DFA------------------------------------------------------------
// SKEL ----------------------------------------------------------------

// [4.0] data tables for the DFA go here -------------------------------
const yyNumRules = 75
const yyEndOfBuffer = 76
var yyAccept = [245]int16{   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       76,   74,   73,   73,   49,   70,   47,   46,   74,   71,
       52,   52,    2,   74,    3,   48,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   38,   39,   62,   63,   56,   75,   68,
       69,   65,   75,   75,   43,   43,   49,    7,   47,   45,
       46,    1,   41,   44,    0,   52,    0,    0,    0,    0,
        8,    4,    6,    5,    9,   48,   51,   51,   51,   51,
       26,   51,   51,   51,   51,   51,   51,   51,   51,   27,
       51,   51,   51,   28,   25,   51,   51,   51,   51,   51,

       51,   51,   51,    0,    0,   62,   64,   59,   60,   58,
       57,   64,   68,   65,   65,   67,   66,   42,   44,   53,
       52,   55,   54,   31,   24,   32,   51,   51,   51,   51,
       51,   30,   51,   51,   51,   51,   51,   51,   51,   51,
       23,   51,   51,   51,   51,   51,   51,   51,   17,   72,
        0,    0,    0,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   50,   51,   13,   51,   51,
       12,   51,   29,   21,   16,    0,    0,    0,    0,    0,
       72,   61,   15,   51,   51,   51,   22,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,    0,    0,   51,

       51,   51,   51,   51,   11,   37,   51,   50,   51,   19,
       51,   51,    0,    0,    0,    0,    0,   72,   51,   51,
       51,   51,   51,   40,   35,   10,   14,    0,   72,    0,
        0,    0,   51,   36,   51,   34,   18,    0,    0,    0,
       20,   51,   33,    0,
    }

var yyEc = [256]byte{    0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    1,    1,    1,    8,
        8,    9,    1,    1,    8,   10,   11,   12,   13,   14,
       15,   16,   16,   17,   16,   18,   19,    1,    1,   20,
       21,   22,    8,   23,   24,   25,   24,   24,   24,   24,
       26,   26,   26,   26,   27,   26,   28,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
        8,   29,    8,    1,   30,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   26,   26,   40,   41,   42,
       43,   44,   26,   45,   46,   47,   48,   49,   50,   51,
       52,   53,   54,    8,   55,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,
    }

var yyMeta = [56]byte{    0,
        1,    2,    3,    1,    4,    1,    1,    2,    5,    6,
        7,    8,    8,    8,    8,    8,    8,    8,    8,    1,
        9,    1,    1,   10,   10,   11,   12,   12,   13,   11,
       10,   10,   10,   10,   10,   10,   11,   11,   11,   11,
       11,   11,   12,   11,   11,   11,   11,   11,   11,   11,
       12,   11,   11,    1,    1,
    }

var yyBase = [267]uint16{   0,
        0,    0,   53,   54,   57,   58,    0,    0,  357,  350,
      358,  646,  646,  646,  336,  646,    0,  347,  345,   53,
       53,   57,   45,  331,   49,    0,    0,   32,  308,  308,
       58,  309,   34,   42,  296,   54,  291,  287,  287,   50,
      294,  290,  285,  316,  646,    0,  646,  646,   86,    0,
      646,   59,  315,  646,  646,  314,  303,  646,    0,  646,
      314,  646,  646,    0,  104,    0,  297,  296,   97,    0,
      646,  646,  646,  646,  646,    0,    0,  280,   73,  286,
        0,  276,  270,  276,  275,  269,  273,  269,  261,   91,
      257,  256,   93,    0,    0,  263,  261,  253,  262,  248,

      253,  251,  237,   81,  118,    0,  646,  646,  646,  646,
      646,    0,    0,  235,  646,  646,  646,  646,    0,  129,
      646,  137,    0,    0,    0,    0,  241,  121,  234,  229,
      239,    0,  233,  240,  228,  230,  117,  236,  237,  236,
        0,  217,  230,  225,  222,  227,  214,  225,    0,  646,
      250,  167,    0,  219,  212,  219,  197,  213,  201,  194,
      212,  197,  193,  214,  216,  196,  189,    0,  180,  194,
        0,  179,    0,    0,    0,  211,  208,  221,    0,  147,
        0,  646,    0,  171,  178,  172,    0,  176,  171,  173,
      165,  177,  175,  174,  173,  160,  169,  275,  148,  166,

      162,  154,  143,  150,    0,    0,  159,    0,  147,    0,
      155,  143,  329,    0,  383,  177,  151,    0,  144,  131,
      137,  104,  100,    0,    0,    0,    0,  152,  122,  155,
       92,  156,   60,    0,   52,    0,    0,  162,    0,  163,
        0,   46,    0,  646,  438,  451,  464,  477,  483,  488,
      496,  503,  508,  513,  524,  534,  546,  559,  571,  584,
      590,  593,  603,  616,  622,  632,
    }

var yyDef = [267]int16{   0,
      244,    1,  245,  245,  246,  246,  247,  247,  248,  248,
      244,  244,  244,  244,  249,  244,  250,  251,  244,  244,
      252,  252,  244,  244,  244,  253,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  255,  244,  256,  244,  244,  257,  258,
      244,  244,  259,  244,  244,  244,  249,  244,  250,  244,
      251,  244,  244,  260,  244,   22,  244,  244,  244,  261,
      244,  244,  244,  244,  244,  253,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,

      254,  254,  254,  255,  244,  256,  244,  244,  244,  244,
      244,  262,  258,  244,  244,  244,  244,  244,  260,  244,
      244,  244,  261,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  244,
      263,  264,  265,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  263,  244,  264,  178,  178,
      178,  244,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  266,  178,  254,

      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  266,  213,  263,  178,  213,  213,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  263,  263,  178,
      213,  213,  254,  254,  254,  254,  254,  263,  213,  213,
      254,  254,  254,    0,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,
    }

var yyNxt = [702]uint16{   0,
       12,   13,   14,   15,   16,   17,   18,   12,   12,   19,
       20,   21,   22,   22,   22,   22,   22,   22,   22,   23,
       24,   25,   26,   27,   27,   27,   27,   27,   12,   27,
       28,   27,   29,   27,   30,   31,   32,   27,   33,   27,
       34,   35,   36,   37,   38,   39,   40,   41,   27,   42,
       43,   27,   27,   44,   45,   47,   47,   48,   48,   51,
       51,   63,   65,   64,   71,   72,   65,   52,   52,   74,
       75,   78,   91,   79,   89,   90,   92,   80,   81,   67,
       68,   49,   49,   67,   68,   53,   53,   99,   84,   94,
      108,  105,  243,  242,  100,   69,   85,  114,   95,  244,

       86,  241,  240,   70,  115,   87,  125,  244,  122,  122,
      122,  122,  122,  122,  109,  120,  120,  120,  120,  120,
      120,  120,  120,  136,  126,  140,  151,  110,  152,  164,
      177,  165,  111,  237,  166,  150,  112,  137,  236,  141,
      120,  120,  120,  120,  120,  120,  120,  120,  122,  122,
      122,  122,  122,  122,  155,  198,  198,  199,  199,  231,
      238,  232,  239,  198,  231,  199,  232,  156,  179,  104,
      177,  231,  215,  232,  179,  235,  234,  180,  179,  179,
      179,  179,  179,  179,  179,  179,  233,  230,  227,  226,
      179,  179,  225,  224,  223,  222,  221,  179,  179,  179,

      179,  179,  179,  220,  219,  212,  211,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  201,  200,  104,  177,
      197,  181,  179,  104,  196,  195,  194,  193,  179,  166,
      166,  180,  179,  179,  179,  179,  179,  179,  179,  179,
      192,  191,  190,  189,  179,  179,  188,  187,  186,  185,
      184,  179,  179,  179,  179,  179,  179,  183,  177,  175,
      137,  174,  173,  172,  171,  170,  169,  168,  167,  163,
      162,  161,  160,  159,  158,  181,  214,  215,  157,  154,
      115,  149,  214,  216,  148,  217,  214,  214,  214,  214,
      214,  214,  214,  214,  147,  146,  145,  144,  214,  214,

      143,  142,  139,  138,  135,  214,  214,  214,  214,  214,
      214,  134,  133,  132,  131,  130,  129,  128,  127,  124,
      121,  121,   60,  244,  118,  117,  105,  103,  102,  218,
      214,  215,  101,   98,   97,   96,  214,  216,   93,  217,
      214,  214,  214,  214,  214,  214,  214,  214,   88,   83,
       82,   73,  214,  214,   62,   60,   58,  244,   56,  214,
      214,  214,  214,  214,  214,   56,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  218,  215,  215,  244,  244,  244,  244,
      215,  177,  244,  228,  215,  215,  215,  215,  215,  215,

      215,  215,  244,  244,  244,  244,  215,  215,  244,  244,
      244,  244,  244,  215,  215,  215,  215,  215,  215,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  229,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       57,   57,   57,   57,   57,   59,  244,   59,   59,   59,

       61,  244,  244,   61,  244,   61,   61,   61,   66,  244,
       66,  244,  244,  244,   66,   76,  244,   76,   76,   76,
       77,  244,   77,   77,   77,  104,  104,  244,  244,  244,
      104,  104,  244,  104,  106,  106,  244,  244,  106,  106,
      106,  106,  106,  106,  106,  106,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  113,
      113,  244,  113,  113,  113,  244,  113,  113,  113,  113,
      113,  116,  116,  244,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  119,  119,  244,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  123,  244,  123,

      153,  244,  153,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  182,
      244,  182,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,   11,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,

      244,
    }

var yyChk = [702]int16{   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,    3,    4,    5,
        6,   20,   21,   20,   23,   23,   22,    5,    6,   25,
       25,   28,   34,   28,   33,   33,   34,   28,   28,   21,
       21,    3,    4,   22,   22,    5,    6,   40,   31,   36,
       49,  104,  242,  235,   40,   21,   31,   52,   36,   22,

       31,  233,  231,   21,   52,   31,   79,   22,   69,   69,
       69,   69,   69,   69,   49,   65,   65,   65,   65,   65,
       65,   65,   65,   90,   79,   93,  105,   49,  105,  137,
      229,  137,   49,  223,  137,  104,   49,   90,  222,   93,
      120,  120,  120,  120,  120,  120,  120,  120,  122,  122,
      122,  122,  122,  122,  128,  180,  199,  180,  199,  217,
      228,  217,  228,  230,  232,  230,  232,  128,  152,  152,
      238,  240,  238,  240,  152,  221,  220,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  219,  216,  212,  211,
      152,  152,  209,  207,  204,  203,  202,  152,  152,  152,

      152,  152,  152,  201,  200,  197,  196,  195,  194,  193,
      192,  191,  190,  189,  188,  186,  185,  184,  177,  176,
      172,  152,  178,  178,  170,  169,  167,  166,  178,  165,
      164,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      163,  162,  161,  160,  178,  178,  159,  158,  157,  156,
      155,  178,  178,  178,  178,  178,  178,  154,  151,  148,
      147,  146,  145,  144,  143,  142,  140,  139,  138,  136,
      135,  134,  133,  131,  130,  178,  198,  198,  129,  127,
      114,  103,  198,  198,  102,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  101,  100,   99,   98,  198,  198,

       97,   96,   92,   91,   89,  198,  198,  198,  198,  198,
      198,   88,   87,   86,   85,   84,   83,   82,   80,   78,
       68,   67,   61,   57,   56,   53,   44,   43,   42,  198,
      213,  213,   41,   39,   38,   37,  213,  213,   35,  213,
      213,  213,  213,  213,  213,  213,  213,  213,   32,   30,
       29,   24,  213,  213,   19,   18,   15,   11,   10,  213,
      213,  213,  213,  213,  213,    9,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  213,  215,  215,    0,    0,    0,    0,
      215,  215,    0,  215,  215,  215,  215,  215,  215,  215,

      215,  215,    0,    0,    0,    0,  215,  215,    0,    0,
        0,    0,    0,  215,  215,  215,  215,  215,  215,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  215,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      249,  249,  249,  249,  249,  250,    0,  250,  250,  250,

      251,    0,    0,  251,    0,  251,  251,  251,  252,    0,
      252,    0,    0,    0,  252,  253,    0,  253,  253,  253,
      254,    0,  254,  254,  254,  255,  255,    0,    0,    0,
      255,  255,    0,  255,  256,  256,    0,    0,  256,  256,
      256,  256,  256,  256,  256,  256,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  258,
      258,    0,  258,  258,  258,    0,  258,  258,  258,  258,
      258,  259,  259,    0,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  260,  260,    0,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  261,    0,  261,

      262,    0,  262,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  265,
        0,  265,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,

      244,
    }

/* Table of booleans, true if rule could match eol. */
var yyRuleCanMatchEol = [76]int32{   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,     };

//line lexer.l:1
/*
Copyright (c) 2007-2013. The YARA Authors. All Rights Reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation and/or
other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors
may be used to endorse or promote products derived from this software without
specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
/* Lexical analyzer for YARA */

//line lexer.l:72

 

 

// Define a constant for end-of-file
const eof = 0




//line lexer.go:487
// SKEL ----------------------------------------------------------------

const yyInitial  = 0
const str = 1
const regexp = 2
const include = 3
const comment = 4

const yyReadBufSize = 16384

func (yy *Scanner) input(offset, maxRead int) int {

// [5.0] fread()/read() definition of yy_INPUT goes here ---------------
// nothing here, all moved to skeleton
// SKEL ----------------------------------------------------------------

	if yy.Interactive {
		b := make([]byte, 1)
		var n int
		for n = 0; n < maxRead; n++ {
			nn, err := yy.inputFile.Read(b)
			if err != nil && err != io.EOF {
				log.Panicln("Reading 1 byte:", err)
			}
			if nn < 1 {
				break
			}
			yy.chBuf[offset+n] = b[0]
			if b[0] == '\n' {
				n++
				break
			}
		}
		return n
	}

	n, err := yy.inputFile.Read(yy.chBuf[offset:offset+maxRead])
	if err != nil  && err != io.EOF {
		log.Panicf("Reading %d bytes: %v\n", maxRead, err)
	}
	return n
}

/* [6.0] YY_RULE_SETUP definition goes here --------------------------*/

// SKEL ----------------------------------------------------------------

// The main scanner function which does all the work.
func (yy *Scanner) Lex() YYtype {
	var yyCurrentState int
	var yyBp, yyCp int
	var yyAct int
	var yytext []byte
	var yyleng int
	var yylineno int
	_ = yytext
	_ = yyleng
	_ =  yylineno 

	var (
    collectText       bool    // true when reading string/regex/hex text
    text              []byte  // collects text while reading a string/regex/hex
    YYtext            string  // each action sets this to the current yytext
  )

	if !yy.init {
		yy.init = true
		
		if yy.In == nil {
			yy.In = os.Stdin
		}
		if yy.Out == nil {
			yy.Out = os.Stdout
		}
		yy.initBuffer(yy.In)
		yy.loadBufferState()
	}

	yyout := yy.Out
	_ = yyout

// [7.0] user's declarations go here -----------------------------------
//line lexer.l:112


//line lexer.go:573
// SKEL ----------------------------------------------------------------

	for { // loops until end-of-file is reached

// [8.0] yy''more-related code goes here -------------------------------
// SKEL ----------------------------------------------------------------

		yyCp = yy.cBufP

		/* Support of yytext. */
		yy.chBuf[yyCp] = yy.holdChar

		// yyBp points to the position in yy_ch_buf of the start of
		// the current run.
		yyBp = yyCp

// [9.0] code to set up and find next match goes here ------------------
		yyCurrentState = yy.start
yyMatch:
		for {
			yyC := int(yyEc[yy.chBuf[yyCp]])
						if yyAccept[yyCurrentState] != 0 {
				yy.lastAcceptingState = yyCurrentState
				yy.lastAcceptingCpos = yyCp
			}
			for int(yyChk[int(yyBase[yyCurrentState])+yyC]) != yyCurrentState {
				yyCurrentState = int(yyDef[yyCurrentState])
				if yyCurrentState >= 245 {
					yyC = int(yyMeta[yyC])
				}
			}
			yyCurrentState = int(yyNxt[int(yyBase[yyCurrentState])+yyC])
			yyCp++
			if yyCurrentState == 244 {
				break
			}
		}
		yyCp = yy.lastAcceptingCpos
		yyCurrentState = yy.lastAcceptingState
// SKEL ----------------------------------------------------------------

	yyFindAction:

// [10.0] code to find the action number goes here ---------------------
		yyAct = int(yyAccept[yyCurrentState])
// SKEL ----------------------------------------------------------------

		yy.textPtr = yyBp

// [2.0] code to fiddle yytext and yyleng for yy''more() goes here -------
	yyleng = yyCp - yyBp
// SKEL ----------------------------------------------------------------

		yy.holdChar = yy.chBuf[yyCp]
		yy.chBuf[yyCp] = 0

// [3.0] code to copy yytext_ptr to yytext[] goes here, if %array ------
// SKEL ----------------------------------------------------------------

		yy.cBufP = yyCp
		yytext = yy.chBuf[yy.textPtr:yyCp]
 
// [11.0] code for yylineno update goes here ---------------------------

		if yyAct != yyEndOfBuffer && yyRuleCanMatchEol[yyAct] != 0 {
			for yyl := 0; yyl < yyleng; yyl++ {
				if yytext[yyl] == '\n' {
					yy.Lineno++
				}
			}
		}

// SKEL ----------------------------------------------------------------

	doAction: // This label is used only to access EOF actions.

// [12.0] debug code goes here -----------------------------------------
// SKEL ----------------------------------------------------------------

		switch yyAct { // beginning of action switch

// [13.0] actions go here ----------------------------------------------
			case 0: // must back up
			// undo the effects of yy_DO_BEFORE_ACTION
			yy.chBuf[yyCp] = yy.holdChar
			yyCp = yy.lastAcceptingCpos
			yyCurrentState = yy.lastAcceptingState
			goto yyFindAction

case 1:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }

//line lexer.l:114
{ return _DOT_DOT_;     }
case 2:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:115
{ return _LT_;          }
case 3:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:116
{ return _GT_;          }
case 4:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:117
{ return _LE_;          }
case 5:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:118
{ return _GE_;          }
case 6:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:119
{ return _EQ_;          }
case 7:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:120
{ return _NEQ_;         }
case 8:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:121
{ return _SHIFT_LEFT_;  }
case 9:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:122
{ return _SHIFT_RIGHT_; }
case 10:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:123
{ return _PRIVATE_;     }
case 11:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:124
{ return _GLOBAL_;      }
case 12:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:125
{ return _RULE_;        }
case 13:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:126
{ return _META_;        }
case 14:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:127
{ return _STRINGS_;     }
case 15:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:128
{ return _ASCII_;       }
case 16:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:129
{ return _WIDE_;        }
case 17:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:130
{ return _XOR_;         }
case 18:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:131
{ return _FULLWORD_;    }
case 19:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:132
{ return _NOCASE_;      }
case 20:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:133
{ return _CONDITION_;   }
case 21:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:134
{ return _TRUE_;        }
case 22:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:135
{ return _FALSE_;       }
case 23:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:136
{ return _NOT_;         }
case 24:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:137
{ return _AND_;         }
case 25:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:138
{ return _OR_;          }
case 26:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:139
{ return _AT_;          }
case 27:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:140
{ return _IN_;          }
case 28:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:141
{ return _OF_;          }
case 29:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:142
{ return _THEM_;        }
case 30:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:143
{ return _FOR_;         }
case 31:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:144
{ return _ALL_;         }
case 32:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:145
{ return _ANY_;         }
case 33:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:146
{ return _ENTRYPOINT_;  }
case 34:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:147
{ return _FILESIZE_;    }
case 35:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:148
{ return _MATCHES_;     }
case 36:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:149
{ return _CONTAINS_;    }
case 37:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:150
{ return _IMPORT_;      }
case 38:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:152
{ return _LBRACE_; }
case 39:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:153
{ return _RBRACE_; }
case 40:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:154
{ return _INCLUDE_; }
case 41:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:156
{ yy.start = 1 + 2*  (comment);       }
case 42:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:157
{ yy.start = 1 + 2*  (yyInitial );       }
case 43:
/* rule 43 can match eol */

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:158
{ /* skip comments */   }
case 44:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:161
{ /* skip single-line comments */ }
case (yyEndOfBuffer + yyInitial  + 1) :
	fallthrough
case (yyEndOfBuffer + str + 1) :
	fallthrough
case (yyEndOfBuffer + regexp + 1) :
	fallthrough
case (yyEndOfBuffer + include + 1) :
	fallthrough
case (yyEndOfBuffer + comment + 1) :
//line lexer.l:163
{ return eof }
case 45:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:166
{
  yy.Context.lval.s = string(yytext)
  return _STRING_IDENTIFIER_WITH_WILDCARD_;
}
case 46:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:172
{
  yy.Context.lval.s = string(yytext)
  return _STRING_IDENTIFIER_;
}
case 47:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:178
{
  yy.Context.lval.s = string(yytext)
  return _STRING_COUNT_;
}
case 48:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:184
{
  yy.Context.lval.s = string(yytext)
  return _STRING_OFFSET_;
}
case 49:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:190
{
  yy.Context.lval.s = string(yytext)
  return _STRING_LENGTH_;
}
case 50:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:196
{
  yy.Context.lval.s = string(yytext)
  return _INTEGER_FUNCTION_;
}
case 51:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:202
{
  yy.Context.lval.s = string(yytext)
  return _IDENTIFIER_;
}
case 52:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:208
{
  var err error
  s := strings.TrimRight(YYtext, "MKB")
  yy.Context.lval.i64, err = strconv.ParseInt(s, 10, 64)
  if err != nil {
    panic(
      gyperror.Error{
        gyperror.NumberConversionError,
        fmt.Sprintf("%s", err),
      },
    )
  }

  if strings.HasSuffix(YYtext, "KB") {
      if yy.Context.lval.i64 > math.MaxInt64 / 1024 {
        panic(
          gyperror.Error{
            gyperror.IntegerOverflowError,
            fmt.Sprintf("Found %s; Max: %d", YYtext, math.MaxInt64),
          },
        )
      } else {
        yy.Context.lval.i64 *= 1024
      }
  } else if strings.HasSuffix(YYtext, "MB") {
      if yy.Context.lval.i64 > math.MaxInt64 / 1048576 {
        panic(
          gyperror.Error{
            gyperror.IntegerOverflowError,
            fmt.Sprintf("Found %s; Max: %d", YYtext, math.MaxInt64),
          },
        )
      } else {
          yy.Context.lval.i64 *= 1048576
      }
  }
  return _NUMBER_;
}
case 53:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:247
{
  return _DOUBLE_;
}
case 54:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:251
{
  var err error
  yy.Context.lval.i64, err = strconv.ParseInt(YYtext, 0, 64)
  if err != nil {
    panic(
      gyperror.Error{
        gyperror.NumberConversionError,
        fmt.Sprintf("%s", err),
      },
    )
  }

  return _NUMBER_;
}
case 55:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:266
{
  var err error
  s := strings.TrimLeft(YYtext, "0o")
  yy.Context.lval.i64, err = strconv.ParseInt(s, 8, 64)
  if err != nil {
    panic(
      gyperror.Error{
        gyperror.NumberConversionError,
        fmt.Sprintf("%s", err),
      },
    )
  }
  return _NUMBER_;
}
case 56:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:282
{     /* saw closing quote - all done */

  // NOTE: text will end with `"` char
  collectText = false
  yy.Context.lval.s = strings.TrimSuffix(string(text), `"`)

  yy.start = 1 + 2*  (yyInitial );

  return _TEXT_STRING_;
}
case 57:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:294
{
}
case 58:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:298
{
}
case 59:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:302
{
}
case 60:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:306
{
}
case 61:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:310
{
}
case 62:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:314
{ }
case 63:
/* rule 63 can match eol */

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:317
{
  panic(gyperror.Error{ gyperror.UnterminatedStringError, "" })
}
case 64:
/* rule 64 can match eol */

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:322
{
  panic(gyperror.Error{ gyperror.IllegalEscapeSequenceError, "" })
}
case 65:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:327
{
  collectText = false

  txt := strings.TrimSuffix(string(text), YYtext)

  var mods ast.StringModifiers

  for _, c := range YYtext {
      switch c {
      case 'i':
          mods.I = proto.Bool(true)

      case 's':
          mods.S = proto.Bool(true)

      case '/':
          // Ignore

      default:
          // Should be impossible
          panic(
            gyperror.Error{
              gyperror.InvalidRegexModifierError,
              fmt.Sprintf(`"%c"`, c),
            },
          )
      }
  }

  yy.Context.lval.reg = ast.Regexp {
      Text: &txt,
      Modifiers: &mods,
  }

  yy.start = 1 + 2*  (yyInitial );
  return _REGEXP_;
}
case 66:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:366
{
}
case 67:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:370
{
}
case 68:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:374
{ }
case 69:
/* rule 69 can match eol */

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:377
{
  panic(gyperror.Error{ gyperror.UnterminatedRegexError, "" })
}
case 70:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:382
{
  collectText = true
  text = []byte{}
  yy.start = 1 + 2*  (str);
}
case 71:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:389
{
  collectText = true
  text = []byte{}
  yy.start = 1 + 2*  (regexp);
}
case 72:
/* rule 72 can match eol */

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:396
{
  // Match hex-digits with whitespace or comments. The latter are stripped
  // out by hex_lexer.l

  // NOTE: The above comment may not apply. We plan to not use hex_lexer.l

  // No need to collect like str and regexp start conditions
  hexReader := strings.NewReader(YYtext)

  hexString, err := hex.Parse(hexReader)
  if err != nil {
    panic(err)
  }
  yy.Context.lval.hextokens = &hexString

  return _HEX_STRING_;
}
case 73:
/* rule 73 can match eol */

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:415
/* skip whitespace */
case 74:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:417
{

  r := int(yytext[0])

  if r >= 32 && r < 127 {
    return r
  }

  panic(gyperror.Error{ gyperror.NonAsciiByteError, fmt.Sprintf(`"%d"`, r) })
}
case 75:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    text = append(text, yytext...)
  }


//line lexer.l:428
yyout.Write(yytext) 
//line lexer.go:1756
// SKEL ----------------------------------------------------------------

		case yyEndOfBuffer:
			/* Amount of text matched not including the EOB char. */
			yyAmountOfMatchedText := yyCp - yy.textPtr - 1

			/* Undo the effects of yy_DO_BEFORE_ACTION. */
			yy.chBuf[yyCp] = yy.holdChar
			 
			if yy.bufferStatus == yyBufferNew {
				/* We're scanning a new file or input source.  It's
				 * possible that this happened because the user
				 * just pointed yyin at a new source and called
				 * yylex().  If so, then we have to assure
				 * consistency between yy_CURRENT_BUFFER and our
				 * globals.  Here is the right place to do so, because
				 * this is the first action (other than possibly a
				 * back-up) that will match for the new input source.
				 */
				yy.nChars = yy.bufNChars
				yy.inputFile = yy.In
				yy.bufferStatus = yyBufferNormal
			}

			/* Note that here we test for yy_c_buf_p "<=" to the position
			 * of the first EOB in the buffer, since yy_c_buf_p will
			 * already have been incremented past the NUL character
			 * (since all states make transitions on EOB to the
			 * end-of-buffer state).  Contrast this with the test
			 * in input().
			 */
			if yy.cBufP <= yy.nChars {
				/* This was really a NUL. */
				var yyNextState int

				yy.cBufP = yy.textPtr + yyAmountOfMatchedText

				yyCurrentState = yy.getPreviousState()

				/* Okay, we're now positioned to make the NUL
				 * transition.  We couldn't have
				 * yy_get_previous_state() go ahead and do it
				 * for us because it doesn't know how to deal
				 * with the possibility of jamming (and we don't
				 * want to build jamming into it because then it
				 * will run more slowly).
				 */

				yyNextState = yy.tryNulTrans(yyCurrentState)

				yyBp = yy.textPtr + 0 

				if yyNextState != 0 {
					/* Consume the NUL. */
					yy.cBufP++
					yyCp = yy.cBufP
					yyCurrentState = yyNextState
					goto yyMatch
				} else {

// [14.0] code to do back-up for compressed tables and set up yy_cp goes here
				yyCp = yy.lastAcceptingCpos
				yyCurrentState = yy.lastAcceptingState
// SKEL ----------------------------------------------------------------

					goto yyFindAction
				}

			} else {

				switch yy.getNextBuffer() {
				case eobActEndOfFile:
					yy.didBufferSwitchOnEof = false

					if yy.Wrap(yy) {
						// Note: because we've taken care in
						// yy_get_next_buffer() to have set up
						// yytext, we can now set up
						// yy.cBufP so that if some total
						// hoser (like flex itself) wants to
						// call the scanner after we return the
						// yy_NULL, it'll still work - another
						// yy_NULL will get returned.
						yy.cBufP = yy.textPtr + 0 

						yyAct = (yyEndOfBuffer + ((yy.start - 1) / 2)  + 1) 
						goto doAction
					} else {
						if !yy.didBufferSwitchOnEof {
							yy.NewFile()
						}
					}
				case eobActContinueScan:
					yy.cBufP = yy.textPtr + yyAmountOfMatchedText

					yyCurrentState = yy.getPreviousState()

					yyCp = yy.cBufP
					yyBp = yy.textPtr + 0 
					goto yyMatch
				case eobActLastMatch:
					yy.cBufP = yy.nChars

					yyCurrentState = yy.getPreviousState()

					yyCp = yy.cBufP
					yyBp = yy.textPtr + 0 
					goto yyFindAction
				}
			}

		default:
			log.Panicln("fatal flex scanner internal error--no action found:", yyAct)
		} // end of action switch
	} // end of scanning one token
	var yyvalue YYtype
	return yyvalue
} // end of yylex

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
func (yy *Scanner) getNextBuffer() int {

	var numberToMove int
	var retval int

	if yy.cBufP > yy.nChars+1 {
		log.Panic("fatal flex scanner internal error--end of buffer missed")
	}

	if !yy.fillBuffer {
		// Don't try to fill the buffer, so this is an EOF.
		if yy.cBufP-yy.textPtr-0  == 1 {
			// We matched a single character, the EOB, so
			// treat this as a final EOF.
			return eobActEndOfFile
		} else {
			// We matched some text prior to the EOB, first
			// process it.
			return eobActLastMatch
		}
	}

	// Try to read more data.

	// First move last chars to start of buffer.
	numberToMove = yy.cBufP - yy.textPtr - 1

	copy(yy.chBuf, yy.chBuf[yy.textPtr:yy.textPtr+numberToMove])

	if yy.bufferStatus == yyBufferEofPending {
		// don't do the read, it's not guaranteed to return an EOF,
		// just force an EOF
		yy.nChars = 0
		yy.bufNChars = 0
	} else {
		numToRead := yy.bufSize - numberToMove - 1

		for numToRead <= 0 {
			// Not enough room in the buffer - grow it.

			yyCBufPOffset := yy.cBufP

			new_size := yy.bufSize * 2

			if new_size <= 0 {
				yy.bufSize += yy.bufSize / 8
			} else {
				yy.bufSize *= 2
			}

			// Include room in for 2 EOB chars.
			bb := make([]byte, yy.bufSize+2-len(yy.chBuf))
			yy.chBuf = append(yy.chBuf, bb...)

			yy.cBufP = yyCBufPOffset

			numToRead = yy.bufSize - numberToMove - 1

		}

		if numToRead > yyReadBufSize {
			numToRead = yyReadBufSize
		}

		// Read in more data.
		yy.nChars = yy.input(numberToMove, numToRead)
		yy.bufNChars = yy.nChars
	}

	if yy.nChars == 0 {
		if numberToMove == 0  {
			retval = eobActEndOfFile
			yy.Restart(yy.In)
		} else {
			retval = eobActLastMatch
			yy.bufferStatus = yyBufferEofPending
		}
	} else {
		retval = eobActContinueScan
	}

	if yy.nChars+numberToMove > yy.bufSize {
		// Extend the array by 50%, plus the number we really need. *
		newSize := yy.nChars + numberToMove + (yy.nChars >> 1)
		if leng := len(yy.chBuf); leng < newSize {
			chBuf := make([]byte, newSize-leng)
			yy.chBuf = append(yy.chBuf, chBuf...)
		}
	}

	yy.nChars += numberToMove
	//yy.bufNChars += numberToMove // TODO: missing in C skel, bug?
	yy.chBuf[yy.nChars] = yyEndOfBufferChar
	yy.chBuf[yy.nChars+1] = yyEndOfBufferChar

	yy.textPtr = 0

	return retval
}

/* yy_get_previous_state - get the state just before the EOB char was reached */
func (yy *Scanner) getPreviousState() int {

	var yyCurrentState int
	var yyCp int

// [15.0] code to get the start state into yy_current_state goes here --
	yyCurrentState = yy.start
// SKEL ----------------------------------------------------------------

	for yyCp = yy.textPtr + 0 ; yyCp < yy.cBufP; yyCp++ {

// [16.0] code to find the next state goes here ------------------------
		yyC := yyIfElse(yy.chBuf[yyCp] != 0, int(yyEc[yy.chBuf[yyCp]]), 1)
				if yyAccept[yyCurrentState] != 0 {
			yy.lastAcceptingState = yyCurrentState
			yy.lastAcceptingCpos = yyCp
		}
		for int(yyChk[int(yyBase[yyCurrentState])+yyC]) != yyCurrentState {
			yyCurrentState = int(yyDef[yyCurrentState])
			if yyCurrentState >= 245 {
				yyC = int(yyMeta[yyC])
			}
		}
		yyCurrentState = int(yyNxt[int(yyBase[yyCurrentState])+yyC])
// SKEL ----------------------------------------------------------------

	}
	return yyCurrentState
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *      next_state = yy_try_NUL_trans( current_state );
 */
func (yy *Scanner) tryNulTrans(yyCurrentState int) int {

	var yyIsJam bool
	var yyCp int
	_ = yyCp

// [17.0] code to find the next state, and perhaps do backing up, goes here
	yyCp = yy.cBufP

	yyC := 1
		if yyAccept[yyCurrentState] != 0 {
		yy.lastAcceptingState = yyCurrentState
		yy.lastAcceptingCpos = yyCp
	}
	for int(yyChk[int(yyBase[yyCurrentState])+yyC]) != yyCurrentState {
		yyCurrentState = int(yyDef[yyCurrentState])
		if yyCurrentState >= 245 {
			yyC = int(yyMeta[yyC])
		}
	}
	yyCurrentState = int(yyNxt[int(yyBase[yyCurrentState])+yyC])
	if yyCurrentState == 244 {
		yyIsJam = true
	}
// SKEL ----------------------------------------------------------------

	if yyIsJam {
		return 0
	}
	return yyCurrentState
}

func (yy *Scanner) Input() (byte, error) {

	yy.chBuf[yy.cBufP] = yy.holdChar

	if yy.chBuf[yy.cBufP] == yyEndOfBufferChar {
		// yy_c_buf_p now points to the character we want to return.
		// If this occurs *before* the EOB characters, then it's a
		// valid NUL; if not, then we've hit the end of the buffer.
		if yy.cBufP < yy.nChars {
			// This was really a NUL.
			yy.chBuf[yy.cBufP] = 0
		} else {
			// need more input
			offset := yy.cBufP - yy.textPtr
			yy.cBufP++

			switch yy.getNextBuffer() {
			case eobActLastMatch:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
				yy.Restart(yy.In)

				fallthrough

			case eobActEndOfFile:
				if yy.Wrap(yy) {
					return 0, io.EOF
				}

				if !yy.didBufferSwitchOnEof {
					yy.Restart(yy.In)
				}

				return yy.Input()

			case eobActContinueScan:
				yy.cBufP = yy.textPtr + offset
			}
		}
	}

	c := yy.chBuf[yy.cBufP]
	yy.chBuf[yy.cBufP] = 0	// preserve yytext
	yy.cBufP++
	yy.holdChar = yy.chBuf[yy.cBufP]

// [19.0] update BOL and yylineno --------------------------------------
	if c == '\n' {
		yy.Lineno++
	}
// SKEL ----------------------------------------------------------------

return c, nil
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 *
 * @note This function does not reset the start condition to @c yyInitial  .
 */
func (yy *Scanner) Restart(input_file io.Reader) {
	yy.initBuffer(input_file)
	yy.loadBufferState()
}

func (yy *Scanner) loadBufferState() {
	yy.nChars = yy.bufNChars
	yy.cBufP = yy.bufPos
	yy.textPtr = yy.cBufP
	yy.In = yy.inputFile
	yy.holdChar = yy.chBuf[yy.cBufP]
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
func (yy *Scanner) initBuffer(file io.Reader) {

	yy.flushBuffer()

	yy.inputFile = file

	yy.fillBuffer = true

	yy.Interactive = yy.IsInteractive(file)

}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 *
 */
func (yy *Scanner) flushBuffer() {

	yy.bufNChars = 0

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	yy.chBuf[0] = yyEndOfBufferChar
	yy.chBuf[1] = yyEndOfBufferChar

	yy.bufPos = 0

	yy.atBol = 1
	yy.bufferStatus = yyBufferNew

	yy.loadBufferState()
}

func yyIfElse(b bool, i1, i2 int) int {
	if b {
		return i1
	}
	return i2
}

func YYmain(filenames ...string) (interface{}, error) {

	var errval error

	yy := NewScanner()

	yy.Filename = "<stdin>"

	if len(filenames) > 0 {
		yy.Filename = filenames[0]
		yy.In, errval = os.Open(yy.Filename)
		if errval != nil {
			return nil, errval
		}
		yy.Wrap = func(yyy *Scanner) bool {
			if len(filenames) == 0 {
				// should not happen
				return true
			}
			yyy.In.(*os.File).Close()
			filenames = filenames[1:]
			if len(filenames) == 0 {
				return true
			}
			yyy.Filename = filenames[0]
			yyy.In, errval = os.Open(yyy.Filename)
			if errval != nil {
				return true
			}
			return false
		}
	}

	return yy.Lex(), errval

}

// END OF SKELL --------------------------------------------------------
//line lexer.l:428



