// Code generated by goyacc -p yr -o parser.go grammar.y. DO NOT EDIT.

//line grammar.y:31
package gyp

import __yyfmt__ "fmt"

//line grammar.y:31
import (
	"fmt"
	proto "github.com/golang/protobuf/proto"

	"github.com/VirusTotal/gyp/ast"
	"github.com/VirusTotal/gyp/error"
)

var ParsedRuleset ast.RuleSet

//line grammar.y:147
type yrSymType struct {
	yys int
	i64 int64
	f64 float64
	s   string
	ss  []string

	rm        *ast.RuleModifiers
	m         []*ast.Meta
	mp        *ast.Meta
	mod       *ast.StringModifiers
	reg       ast.Regexp
	regp      *ast.Regexp
	ys        *ast.String
	yss       []*ast.String
	yr        *ast.Rule
	id        *ast.Identifier
	forexp    *ast.ForExpression
	intset    *ast.IntegerSet
	intenum   *ast.IntegerEnumeration
	iterator  *ast.Iterator
	rng       *ast.Range
	strset    *ast.StringSet
	strenumi  *ast.StringEnumeration_StringEnumerationItem
	strenum   *ast.StringEnumeration
	expr      *ast.Expression
	exprs     *ast.Expressions
	hextokens *ast.HexTokens
}

const _END_OF_INCLUDED_FILE_ = 57346
const _DOT_DOT_ = 57347
const _RULE_ = 57348
const _PRIVATE_ = 57349
const _GLOBAL_ = 57350
const _META_ = 57351
const _STRINGS_ = 57352
const _CONDITION_ = 57353
const _IDENTIFIER_ = 57354
const _STRING_IDENTIFIER_ = 57355
const _STRING_COUNT_ = 57356
const _STRING_OFFSET_ = 57357
const _STRING_LENGTH_ = 57358
const _STRING_IDENTIFIER_WITH_WILDCARD_ = 57359
const _NUMBER_ = 57360
const _DOUBLE_ = 57361
const _INTEGER_FUNCTION_ = 57362
const _TEXT_STRING_ = 57363
const _HEX_STRING_ = 57364
const _REGEXP_ = 57365
const _ASCII_ = 57366
const _WIDE_ = 57367
const _XOR_ = 57368
const _NOCASE_ = 57369
const _FULLWORD_ = 57370
const _AT_ = 57371
const _FILESIZE_ = 57372
const _ENTRYPOINT_ = 57373
const _ALL_ = 57374
const _ANY_ = 57375
const _IN_ = 57376
const _OF_ = 57377
const _FOR_ = 57378
const _THEM_ = 57379
const _MATCHES_ = 57380
const _CONTAINS_ = 57381
const _IMPORT_ = 57382
const _TRUE_ = 57383
const _FALSE_ = 57384
const _LBRACE_ = 57385
const _RBRACE_ = 57386
const _INCLUDE_ = 57387
const _OR_ = 57388
const _AND_ = 57389
const _EQ_ = 57390
const _NEQ_ = 57391
const _LT_ = 57392
const _LE_ = 57393
const _GT_ = 57394
const _GE_ = 57395
const _SHIFT_LEFT_ = 57396
const _SHIFT_RIGHT_ = 57397
const _NOT_ = 57398
const UNARY_MINUS = 57399

var yrToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"_END_OF_INCLUDED_FILE_",
	"_DOT_DOT_",
	"_RULE_",
	"_PRIVATE_",
	"_GLOBAL_",
	"_META_",
	"_STRINGS_",
	"_CONDITION_",
	"_IDENTIFIER_",
	"_STRING_IDENTIFIER_",
	"_STRING_COUNT_",
	"_STRING_OFFSET_",
	"_STRING_LENGTH_",
	"_STRING_IDENTIFIER_WITH_WILDCARD_",
	"_NUMBER_",
	"_DOUBLE_",
	"_INTEGER_FUNCTION_",
	"_TEXT_STRING_",
	"_HEX_STRING_",
	"_REGEXP_",
	"_ASCII_",
	"_WIDE_",
	"_XOR_",
	"_NOCASE_",
	"_FULLWORD_",
	"_AT_",
	"_FILESIZE_",
	"_ENTRYPOINT_",
	"_ALL_",
	"_ANY_",
	"_IN_",
	"_OF_",
	"_FOR_",
	"_THEM_",
	"_MATCHES_",
	"_CONTAINS_",
	"_IMPORT_",
	"_TRUE_",
	"_FALSE_",
	"_LBRACE_",
	"_RBRACE_",
	"_INCLUDE_",
	"_OR_",
	"_AND_",
	"'|'",
	"'^'",
	"'&'",
	"_EQ_",
	"_NEQ_",
	"_LT_",
	"_LE_",
	"_GT_",
	"_GE_",
	"_SHIFT_LEFT_",
	"_SHIFT_RIGHT_",
	"'+'",
	"'-'",
	"'*'",
	"'\\\\'",
	"'%'",
	"_NOT_",
	"'~'",
	"UNARY_MINUS",
	"':'",
	"'='",
	"'('",
	"')'",
	"'.'",
	"'['",
	"']'",
	"','",
}
var yrStatenames = [...]string{}

const yrEofCode = 1
const yrErrCode = 2
const yrInitialStackSize = 16

//line grammar.y:1195

func createOrExpression(terms ...*ast.Expression) (or *ast.Expression) {
	expressions := []*ast.Expression{}
	for _, term := range terms {
		if term.GetOrExpression() == nil {
			expressions = append(expressions, term)
		} else {
			expressions = append(expressions, term.GetOrExpression().GetTerms()...)
		}
	}

	or = &ast.Expression{
		Expression: &ast.Expression_OrExpression{&ast.Expressions{Terms: expressions}},
	}

	return
}

func createAndExpression(terms ...*ast.Expression) (and *ast.Expression) {
	expressions := []*ast.Expression{}
	for _, term := range terms {
		if term.GetAndExpression() == nil {
			expressions = append(expressions, term)
		} else {
			expressions = append(expressions, term.GetAndExpression().GetTerms()...)
		}
	}

	and = &ast.Expression{
		Expression: &ast.Expression_AndExpression{&ast.Expressions{Terms: expressions}},
	}

	return
}

// Strings in YARA rules may contain escaped chars, such as doublequotes (")
// or new lines (\n).
// The strings returned by the lexer contains the backslashes used to escape
// those chars. However, the backslashes are not part of the string to match
// and they should be removed.
// Example:
// -  YARA rule:                  $str = "First line\nSecond line"
// -  decodeEscapedString input:  str  = "First line\\nSecond line"
// -  decodeEscapedString output: out  = "First line\nSecond line"
func decodeEscapedString(str string) (out string) {
	if _, err := fmt.Sscanf(fmt.Sprintf("\"%s\"", str), "%q", &out); err != nil {
		panic(err)
	}

	return out
}

//line yacctab:1
var yrExca = [...]int{
	-1, 1,
	1, -1,
	-2, 15,
	-1, 42,
	23, 34,
	-2, 32,
	-1, 52,
	35, 100,
	-2, 87,
	-1, 107,
	35, 100,
	-2, 87,
	-1, 160,
	70, 63,
	74, 63,
	-2, 66,
	-1, 202,
	70, 64,
	74, 64,
	-2, 66,
}

const yrPrivate = 57344

const yrLast = 393

var yrAct = [...]int{

	52, 170, 49, 141, 67, 148, 213, 178, 223, 111,
	214, 73, 53, 64, 65, 66, 166, 61, 62, 60,
	63, 108, 74, 70, 200, 110, 177, 151, 201, 58,
	59, 71, 72, 80, 79, 54, 96, 94, 95, 212,
	50, 51, 80, 79, 217, 97, 98, 89, 90, 91,
	92, 93, 208, 42, 216, 102, 167, 222, 107, 68,
	106, 176, 48, 56, 69, 38, 220, 203, 57, 115,
	116, 114, 142, 112, 113, 150, 109, 73, 105, 205,
	199, 40, 28, 123, 124, 125, 126, 127, 128, 129,
	130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
	140, 120, 121, 26, 147, 122, 17, 149, 81, 82,
	153, 154, 155, 79, 157, 80, 79, 160, 96, 94,
	95, 87, 88, 83, 85, 84, 86, 97, 98, 89,
	90, 91, 92, 93, 196, 96, 94, 95, 39, 55,
	152, 18, 104, 165, 97, 98, 89, 90, 91, 92,
	93, 168, 30, 74, 73, 118, 64, 65, 66, 5,
	61, 62, 60, 63, 99, 74, 91, 92, 93, 100,
	197, 194, 58, 59, 71, 72, 96, 94, 95, 35,
	77, 202, 37, 117, 13, 97, 98, 89, 90, 91,
	92, 93, 8, 204, 101, 7, 143, 207, 221, 210,
	4, 175, 68, 209, 78, 36, 146, 69, 96, 94,
	95, 103, 198, 156, 41, 219, 31, 97, 98, 89,
	90, 91, 92, 93, 89, 90, 91, 92, 93, 145,
	215, 33, 171, 174, 218, 73, 172, 64, 65, 66,
	23, 61, 62, 60, 63, 20, 74, 96, 94, 95,
	191, 14, 25, 58, 59, 22, 97, 98, 89, 90,
	91, 92, 93, 96, 94, 95, 164, 188, 187, 211,
	189, 190, 97, 98, 89, 90, 91, 92, 93, 9,
	11, 12, 76, 68, 75, 173, 27, 15, 69, 96,
	94, 95, 103, 192, 1, 193, 169, 206, 97, 98,
	89, 90, 91, 92, 93, 81, 82, 195, 144, 158,
	159, 152, 32, 6, 10, 96, 94, 95, 87, 88,
	83, 85, 84, 86, 97, 98, 89, 90, 91, 92,
	93, 44, 119, 163, 43, 162, 96, 94, 95, 186,
	161, 179, 34, 24, 29, 97, 98, 89, 90, 91,
	92, 93, 94, 95, 46, 47, 21, 19, 16, 2,
	97, 98, 89, 90, 91, 92, 93, 95, 3, 0,
	0, 184, 0, 45, 97, 98, 89, 90, 91, 92,
	93, 97, 98, 89, 90, 91, 92, 93, 181, 180,
	185, 182, 183,
}
var yrPact = [...]int{

	-1000, 155, -1000, -1000, 171, -1000, 273, 163, -1000, 239,
	-1000, -1000, -1000, -1000, -1000, 39, 98, 233, 246, 228,
	-1000, 242, 36, -1000, -1000, 15, 204, 220, 192, 204,
	-1000, -3, 94, 14, 192, -1000, -15, -1000, 313, -1000,
	-1, -1000, 158, -1000, -1000, 186, -1000, -1000, 69, -1000,
	-1000, -1000, 267, 135, 142, 107, -1, -1, -1000, -1000,
	7, -1000, -1000, -1000, -1000, -47, -63, 2, 223, 223,
	-1000, -1000, -1000, -1000, -1000, 162, 132, -1000, -1000, -1,
	-1, 130, 223, 223, 223, 223, 223, 223, 223, 223,
	223, 223, 223, 223, 223, 223, 223, 223, 223, 223,
	3, 194, 87, 223, 38, -1000, -43, 70, 69, 223,
	223, 223, 201, 223, -1, -1000, -1000, -1000, -1000, 259,
	-1000, 66, -1000, 87, 87, 87, 87, 87, 87, 87,
	105, 105, -1000, -1000, -1000, 317, 324, 303, 165, 165,
	87, -1000, 223, -1000, -18, 38, -1000, 241, -1000, 219,
	-1000, -1000, -1000, 215, 160, 128, -1000, -12, -44, -67,
	-1000, 364, 243, -1000, -1000, 288, 65, 200, 13, -46,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1, -1000,
	-1000, -1000, -1000, -1000, -1000, -2, -1000, -1000, -1000, -1000,
	-1000, -1000, 223, 12, 2, -1000, 223, -1000, -1000, -17,
	-1000, 219, -1000, 181, 199, -30, -64, 288, -1, -1000,
	-16, -1000, -1, -1000, 223, -4, -1000, 180, -13, 87,
	-1000, -62, -1000, -1000,
}
var yrPgo = [...]int{

	0, 368, 359, 358, 357, 356, 152, 344, 343, 179,
	342, 341, 340, 339, 335, 333, 332, 314, 313, 312,
	21, 2, 0, 4, 310, 309, 23, 139, 308, 307,
	297, 3, 5, 296, 1, 295, 294, 287, 286, 284,
	282,
}
var yrR1 = [...]int{

	0, 36, 36, 36, 36, 36, 1, 37, 38, 2,
	5, 5, 8, 8, 19, 18, 18, 17, 17, 3,
	3, 4, 4, 7, 7, 6, 6, 6, 6, 6,
	10, 10, 39, 9, 40, 9, 9, 12, 12, 11,
	11, 11, 11, 11, 11, 11, 11, 14, 14, 13,
	13, 13, 13, 13, 16, 16, 15, 23, 23, 23,
	23, 25, 25, 24, 24, 26, 20, 21, 21, 21,
	21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
	21, 21, 21, 21, 21, 21, 21, 21, 21, 29,
	29, 31, 30, 30, 32, 32, 33, 33, 34, 34,
	27, 27, 27, 28, 28, 35, 35, 22, 22, 22,
	22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
	22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
	22, 22, 22,
}
var yrR2 = [...]int{

	0, 0, 2, 2, 3, 2, 2, 0, 0, 11,
	0, 3, 0, 3, 3, 0, 2, 1, 1, 0,
	2, 1, 2, 1, 2, 3, 3, 4, 3, 3,
	1, 2, 0, 5, 0, 5, 4, 0, 2, 1,
	1, 1, 1, 1, 1, 4, 6, 0, 2, 1,
	1, 1, 1, 1, 0, 2, 1, 1, 3, 4,
	4, 0, 1, 1, 3, 1, 1, 1, 1, 3,
	3, 1, 3, 3, 3, 9, 8, 3, 2, 3,
	3, 3, 3, 3, 3, 3, 3, 1, 3, 3,
	1, 5, 1, 3, 3, 1, 1, 3, 1, 1,
	1, 1, 1, 1, 3, 1, 1, 3, 1, 1,
	4, 1, 1, 1, 1, 4, 1, 4, 1, 1,
	2, 3, 3, 3, 3, 3, 3, 3, 3, 2,
	3, 3, 1,
}
var yrChk = [...]int{

	-1000, -36, -2, -1, 45, 4, -18, 40, 21, 6,
	-17, 7, 8, 21, 12, -37, -3, 67, 43, -4,
	12, -5, 9, 12, -8, 10, 67, -38, 67, -7,
	-6, 12, -19, 11, -10, -9, 13, -6, 68, 44,
	67, -9, 68, 21, 18, 60, 41, 42, -20, -21,
	41, 42, -22, 13, 36, -27, 64, 69, 30, 31,
	20, 18, 19, 21, 14, 15, 16, -23, 60, 65,
	-26, 32, 33, 12, 23, -39, -40, 22, 18, 47,
	46, 38, 39, 53, 55, 54, 56, 51, 52, 59,
	60, 61, 62, 63, 49, 50, 48, 57, 58, 29,
	34, -27, -22, 69, 35, -20, -21, -22, -20, 69,
	72, 72, 71, 72, 69, -22, -22, 21, 23, -16,
	-20, -20, -26, -22, -22, -22, -22, -22, -22, -22,
	-22, -22, -22, -22, -22, -22, -22, -22, -22, -22,
	-22, -31, 69, 2, -28, 35, 12, -22, -32, 69,
	37, 70, 70, -22, -22, -22, 12, -22, -25, -24,
	-21, -12, -14, -15, 7, -22, 34, 74, -32, -33,
	-34, 13, 17, 70, 73, 73, 73, 70, 74, -11,
	25, 24, 27, 28, 7, 26, -13, 25, 24, 27,
	28, 7, 5, -35, -23, -29, 69, -31, 12, 67,
	70, 74, -21, 69, -22, 67, -30, -22, 69, -34,
	18, 70, 69, 70, 74, -20, 70, 60, -20, -22,
	70, 18, 70, 70,
}
var yrDef = [...]int{

	1, -2, 2, 3, 0, 5, 0, 0, 4, 0,
	16, 17, 18, 6, 7, 19, 0, 0, 10, 20,
	21, 12, 0, 22, 8, 0, 0, 0, 0, 11,
	23, 0, 0, 0, 13, 30, 0, 24, 0, 9,
	0, 31, -2, 25, 26, 0, 28, 29, 14, 66,
	67, 68, -2, 71, 0, 0, 0, 0, 108, 109,
	0, 111, 112, 113, 114, 116, 118, 119, 0, 0,
	132, 101, 102, 57, 65, 0, 0, 54, 27, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 100, 0, 0, 78, 66, -2, 0, 0,
	0, 0, 0, 0, 61, 120, 129, 37, 47, 36,
	79, 80, 69, 70, 81, 82, 83, 84, 85, 86,
	121, 122, 123, 124, 125, 126, 127, 128, 130, 131,
	72, 73, 0, 74, 0, 0, 103, 0, 77, 0,
	95, 88, 107, 0, 0, 0, 58, 0, 0, 62,
	-2, 33, 35, 55, 56, 0, 0, 0, 0, 0,
	96, 98, 99, 110, 115, 117, 59, 60, 0, 38,
	39, 40, 41, 42, 43, 44, 48, 49, 50, 51,
	52, 53, 0, 0, 105, 106, 0, 90, 104, 0,
	94, 0, -2, 0, 0, 0, 0, 92, 0, 97,
	0, 91, 0, 89, 0, 0, 45, 0, 0, 93,
	76, 0, 75, 46,
}
var yrTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 63, 50, 3,
	69, 70, 61, 59, 74, 60, 71, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 67, 3,
	3, 68, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 72, 62, 73, 49, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 48, 3, 65,
}
var yrTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 51, 52, 53, 54,
	55, 56, 57, 58, 64, 66,
}
var yrTok3 = [...]int{
	0,
}

var yrErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yrDebug        = 0
	yrErrorVerbose = false
)

type yrLexer interface {
	Lex(lval *yrSymType) int
	Error(s string)
}

type yrParser interface {
	Parse(yrLexer) int
	Lookahead() int
}

type yrParserImpl struct {
	lval  yrSymType
	stack [yrInitialStackSize]yrSymType
	char  int
}

func (p *yrParserImpl) Lookahead() int {
	return p.char
}

func yrNewParser() yrParser {
	return &yrParserImpl{}
}

const yrFlag = -1000

func yrTokname(c int) string {
	if c >= 1 && c-1 < len(yrToknames) {
		if yrToknames[c-1] != "" {
			return yrToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yrStatname(s int) string {
	if s >= 0 && s < len(yrStatenames) {
		if yrStatenames[s] != "" {
			return yrStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yrErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yrErrorVerbose {
		return "syntax error"
	}

	for _, e := range yrErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yrTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yrPact[state]
	for tok := TOKSTART; tok-1 < len(yrToknames); tok++ {
		if n := base + tok; n >= 0 && n < yrLast && yrChk[yrAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yrDef[state] == -2 {
		i := 0
		for yrExca[i] != -1 || yrExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yrExca[i] >= 0; i += 2 {
			tok := yrExca[i]
			if tok < TOKSTART || yrExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yrExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yrTokname(tok)
	}
	return res
}

func yrlex1(lex yrLexer, lval *yrSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yrTok1[0]
		goto out
	}
	if char < len(yrTok1) {
		token = yrTok1[char]
		goto out
	}
	if char >= yrPrivate {
		if char < yrPrivate+len(yrTok2) {
			token = yrTok2[char-yrPrivate]
			goto out
		}
	}
	for i := 0; i < len(yrTok3); i += 2 {
		token = yrTok3[i+0]
		if token == char {
			token = yrTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yrTok2[1] /* unknown char */
	}
	if yrDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yrTokname(token), uint(char))
	}
	return char, token
}

func yrParse(yrlex yrLexer) int {
	return yrNewParser().Parse(yrlex)
}

func (yrrcvr *yrParserImpl) Parse(yrlex yrLexer) int {
	var yrn int
	var yrVAL yrSymType
	var yrDollar []yrSymType
	_ = yrDollar // silence set and not used
	yrS := yrrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yrstate := 0
	yrrcvr.char = -1
	yrtoken := -1 // yrrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yrstate = -1
		yrrcvr.char = -1
		yrtoken = -1
	}()
	yrp := -1
	goto yrstack

ret0:
	return 0

ret1:
	return 1

yrstack:
	/* put a state and value onto the stack */
	if yrDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yrTokname(yrtoken), yrStatname(yrstate))
	}

	yrp++
	if yrp >= len(yrS) {
		nyys := make([]yrSymType, len(yrS)*2)
		copy(nyys, yrS)
		yrS = nyys
	}
	yrS[yrp] = yrVAL
	yrS[yrp].yys = yrstate

yrnewstate:
	yrn = yrPact[yrstate]
	if yrn <= yrFlag {
		goto yrdefault /* simple state */
	}
	if yrrcvr.char < 0 {
		yrrcvr.char, yrtoken = yrlex1(yrlex, &yrrcvr.lval)
	}
	yrn += yrtoken
	if yrn < 0 || yrn >= yrLast {
		goto yrdefault
	}
	yrn = yrAct[yrn]
	if yrChk[yrn] == yrtoken { /* valid shift */
		yrrcvr.char = -1
		yrtoken = -1
		yrVAL = yrrcvr.lval
		yrstate = yrn
		if Errflag > 0 {
			Errflag--
		}
		goto yrstack
	}

yrdefault:
	/* default state action */
	yrn = yrDef[yrstate]
	if yrn == -2 {
		if yrrcvr.char < 0 {
			yrrcvr.char, yrtoken = yrlex1(yrlex, &yrrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yrExca[xi+0] == -1 && yrExca[xi+1] == yrstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yrn = yrExca[xi+0]
			if yrn < 0 || yrn == yrtoken {
				break
			}
		}
		yrn = yrExca[xi+1]
		if yrn < 0 {
			goto ret0
		}
	}
	if yrn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yrlex.Error(yrErrorMessage(yrstate, yrtoken))
			Nerrs++
			if yrDebug >= 1 {
				__yyfmt__.Printf("%s", yrStatname(yrstate))
				__yyfmt__.Printf(" saw %s\n", yrTokname(yrtoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yrp >= 0 {
				yrn = yrPact[yrS[yrp].yys] + yrErrCode
				if yrn >= 0 && yrn < yrLast {
					yrstate = yrAct[yrn] /* simulate a shift of "error" */
					if yrChk[yrstate] == yrErrCode {
						goto yrstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yrDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yrS[yrp].yys)
				}
				yrp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yrDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yrTokname(yrtoken))
			}
			if yrtoken == yrEofCode {
				goto ret1
			}
			yrrcvr.char = -1
			yrtoken = -1
			goto yrnewstate /* try again in the same state */
		}
	}

	/* reduction by production yrn */
	if yrDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yrn, yrStatname(yrstate))
	}

	yrnt := yrn
	yrpt := yrp
	_ = yrpt // guard against "declared and not used"

	yrp -= yrR2[yrn]
	// yrp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yrp+1 >= len(yrS) {
		nyys := make([]yrSymType, len(yrS)*2)
		copy(nyys, yrS)
		yrS = nyys
	}
	yrVAL = yrS[yrp+1]

	/* consult goto table to find next state */
	yrn = yrR1[yrn]
	yrg := yrPgo[yrn]
	yrj := yrg + yrS[yrp].yys + 1

	if yrj >= yrLast {
		yrstate = yrAct[yrg]
	} else {
		yrstate = yrAct[yrj]
		if yrChk[yrstate] != -yrn {
			yrstate = yrAct[yrg]
		}
	}
	// dummy call; replaced with literal code
	switch yrnt {

	case 2:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line grammar.y:181
		{
			ParsedRuleset.Rules = append(ParsedRuleset.Rules, yrDollar[2].yr)
		}
	case 3:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line grammar.y:184
		{
			ParsedRuleset.Imports = append(ParsedRuleset.Imports, yrDollar[2].s)
		}
	case 4:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:187
		{
			ParsedRuleset.Includes = append(ParsedRuleset.Includes, yrDollar[3].s)
		}
	case 5:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line grammar.y:190
		{
		}
	case 6:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line grammar.y:196
		{
			yrVAL.s = yrDollar[2].s
		}
	case 7:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:204
		{
			yrVAL.yr = &ast.Rule{
				Modifiers:  yrDollar[1].rm,
				Identifier: proto.String(yrDollar[3].s),
			}

			// Forbid duplicate rules
			for _, r := range ParsedRuleset.Rules {
				if yrDollar[3].s == *r.Identifier {
					err := gyperror.Error{gyperror.DuplicateRuleError, yrDollar[3].s}
					panic(err)
				}
			}
		}
	case 8:
		yrDollar = yrS[yrpt-8 : yrpt+1]
//line grammar.y:219
		{
			// $4 is the rule created in above action
			yrDollar[4].yr.Tags = yrDollar[5].ss

			// Forbid duplicate tags
			idx := make(map[string]struct{})
			for _, t := range yrDollar[5].ss {
				if _, had := idx[t]; had {
					err := gyperror.Error{
						gyperror.DuplicateTagError,
						fmt.Sprintf(
							`"%s" at rule "%s"`,
							yrDollar[4].yr.GetIdentifier(),
							t),
					}
					panic(err)
				}
				idx[t] = struct{}{}
			}

			yrDollar[4].yr.Meta = yrDollar[7].m

			yrDollar[4].yr.Strings = yrDollar[8].yss

			// Forbid duplicate string IDs, except `$` (anonymous)
			idx = make(map[string]struct{})
			for _, s := range yrDollar[8].yss {
				if s.GetId() == "$" {
					continue
				}
				if _, had := idx[*s.Id]; had {
					err := gyperror.Error{
						gyperror.DuplicateStringError,
						fmt.Sprintf(
							`"%s" at rule "%s"`,
							yrDollar[4].yr.GetIdentifier(),
							s.GetId(),
						),
					}
					panic(err)
				}
				idx[*s.Id] = struct{}{}
			}
		}
	case 9:
		yrDollar = yrS[yrpt-11 : yrpt+1]
//line grammar.y:264
		{
			condition := yrDollar[10].expr
			yrDollar[4].yr.Condition = condition
			yrVAL.yr = yrDollar[4].yr
		}
	case 10:
		yrDollar = yrS[yrpt-0 : yrpt+1]
//line grammar.y:273
		{
			yrVAL.m = []*ast.Meta{}
		}
	case 11:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:275
		{
			yrVAL.m = make([]*ast.Meta, 0, len(yrDollar[3].m))
			for _, mpair := range yrDollar[3].m {
				// YARA is ok with duplicate keys; we follow suit
				yrVAL.m = append(yrVAL.m, mpair)
			}
		}
	case 12:
		yrDollar = yrS[yrpt-0 : yrpt+1]
//line grammar.y:286
		{
			yrVAL.yss = []*ast.String{}
		}
	case 13:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:287
		{
			yrVAL.yss = yrDollar[3].yss
		}
	case 14:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:292
		{
			yrVAL.expr = yrDollar[3].expr
		}
	case 15:
		yrDollar = yrS[yrpt-0 : yrpt+1]
//line grammar.y:297
		{
			yrVAL.rm = &ast.RuleModifiers{}
		}
	case 16:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line grammar.y:298
		{
			yrVAL.rm = &ast.RuleModifiers{
				Private: proto.Bool(yrDollar[1].rm.GetPrivate() || yrDollar[2].rm.GetPrivate()),
				Global:  proto.Bool(yrDollar[1].rm.GetGlobal() || yrDollar[2].rm.GetGlobal()),
			}
		}
	case 17:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:308
		{
			yrVAL.rm = &ast.RuleModifiers{Private: proto.Bool(true)}
		}
	case 18:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:309
		{
			yrVAL.rm = &ast.RuleModifiers{Global: proto.Bool(true)}
		}
	case 19:
		yrDollar = yrS[yrpt-0 : yrpt+1]
//line grammar.y:314
		{
			yrVAL.ss = []string{}
		}
	case 20:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line grammar.y:315
		{
			yrVAL.ss = yrDollar[2].ss
		}
	case 21:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:320
		{
			yrVAL.ss = []string{yrDollar[1].s}
		}
	case 22:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line grammar.y:321
		{
			yrVAL.ss = append(yrDollar[1].ss, yrDollar[2].s)
		}
	case 23:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:326
		{
			yrVAL.m = []*ast.Meta{yrDollar[1].mp}
		}
	case 24:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line grammar.y:327
		{
			yrVAL.m = append(yrVAL.m, yrDollar[2].mp)
		}
	case 25:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:333
		{
			yrVAL.mp = &ast.Meta{
				Key:   proto.String(yrDollar[1].s),
				Value: &ast.Meta_Text{yrDollar[3].s},
			}
		}
	case 26:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:340
		{
			yrVAL.mp = &ast.Meta{
				Key:   proto.String(yrDollar[1].s),
				Value: &ast.Meta_Number{yrDollar[3].i64},
			}
		}
	case 27:
		yrDollar = yrS[yrpt-4 : yrpt+1]
//line grammar.y:347
		{
			yrVAL.mp = &ast.Meta{
				Key:   proto.String(yrDollar[1].s),
				Value: &ast.Meta_Number{-yrDollar[4].i64},
			}
		}
	case 28:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:354
		{
			yrVAL.mp = &ast.Meta{
				Key:   proto.String(yrDollar[1].s),
				Value: &ast.Meta_Boolean{true},
			}
		}
	case 29:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:361
		{
			yrVAL.mp = &ast.Meta{
				Key:   proto.String(yrDollar[1].s),
				Value: &ast.Meta_Boolean{false},
			}
		}
	case 30:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:371
		{
			yrVAL.yss = []*ast.String{yrDollar[1].ys}
		}
	case 31:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line grammar.y:372
		{
			yrVAL.yss = append(yrDollar[1].yss, yrDollar[2].ys)
		}
	case 32:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line grammar.y:378
		{
			yrVAL.ys = &ast.String{
				Id: proto.String(yrDollar[1].s),
			}
		}
	case 33:
		yrDollar = yrS[yrpt-5 : yrpt+1]
//line grammar.y:384
		{
			yrDollar[3].ys.Value = &ast.String_Text{&ast.TextString{
				Text:      proto.String(decodeEscapedString(yrDollar[4].s)),
				Modifiers: yrDollar[5].mod,
			}}
			yrVAL.ys = yrDollar[3].ys
		}
	case 34:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line grammar.y:392
		{
			yrVAL.ys = &ast.String{
				Id: proto.String(yrDollar[1].s),
			}
		}
	case 35:
		yrDollar = yrS[yrpt-5 : yrpt+1]
//line grammar.y:398
		{
			yrDollar[3].ys.Value = &ast.String_Regexp{&ast.Regexp{
				Text: yrDollar[4].reg.Text,
			}}

			yrDollar[5].mod.I = yrDollar[4].reg.Modifiers.I
			yrDollar[5].mod.S = yrDollar[4].reg.Modifiers.S

			yrDollar[3].ys.GetRegexp().Modifiers = yrDollar[5].mod

			yrVAL.ys = yrDollar[3].ys
		}
	case 36:
		yrDollar = yrS[yrpt-4 : yrpt+1]
//line grammar.y:411
		{
			yrVAL.ys = &ast.String{
				Id:    proto.String(yrDollar[1].s),
				Value: &ast.String_Hex{yrDollar[3].hextokens},
			}
		}
	case 37:
		yrDollar = yrS[yrpt-0 : yrpt+1]
//line grammar.y:422
		{
			yrVAL.mod = &ast.StringModifiers{}
		}
	case 38:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line grammar.y:426
		{
			proto.Merge(yrDollar[1].mod, yrDollar[2].mod)
			yrVAL.mod = yrDollar[1].mod
		}
	case 39:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:434
		{
			yrVAL.mod = &ast.StringModifiers{Wide: proto.Bool(true)}
		}
	case 40:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:435
		{
			yrVAL.mod = &ast.StringModifiers{Ascii: proto.Bool(true)}
		}
	case 41:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:436
		{
			yrVAL.mod = &ast.StringModifiers{Nocase: proto.Bool(true)}
		}
	case 42:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:437
		{
			yrVAL.mod = &ast.StringModifiers{Fullword: proto.Bool(true)}
		}
	case 43:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:438
		{
			yrVAL.mod = &ast.StringModifiers{Private: proto.Bool(true)}
		}
	case 44:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:440
		{
			yrVAL.mod = &ast.StringModifiers{
				Xor:    proto.Bool(true),
				XorMin: proto.Int32(0),
				XorMax: proto.Int32(255),
			}
		}
	case 45:
		yrDollar = yrS[yrpt-4 : yrpt+1]
//line grammar.y:448
		{
			if yrDollar[3].i64 < 0 || yrDollar[3].i64 > 255 {
				err := gyperror.Error{Code: gyperror.InvalidStringModifierError}
				panic(err)
			}

			yrVAL.mod = &ast.StringModifiers{
				Xor:    proto.Bool(true),
				XorMin: proto.Int32(int32(yrDollar[3].i64)),
				XorMax: proto.Int32(int32(yrDollar[3].i64)),
			}
		}
	case 46:
		yrDollar = yrS[yrpt-6 : yrpt+1]
//line grammar.y:461
		{
			if yrDollar[3].i64 < 0 {
				err := gyperror.Error{
					gyperror.InvalidStringModifierError,
					"lower bound for xor range exceeded (min: 0)"}
				panic(err)
			}

			if yrDollar[5].i64 > 255 {
				err := gyperror.Error{
					gyperror.InvalidStringModifierError,
					"upper bound for xor range exceeded (max: 255)"}
				panic(err)
			}

			if yrDollar[3].i64 > yrDollar[5].i64 {
				err := gyperror.Error{
					gyperror.InvalidStringModifierError,
					"xor lower bound exceeds upper bound"}
				panic(err)
			}

			yrVAL.mod = &ast.StringModifiers{
				Xor:    proto.Bool(true),
				XorMin: proto.Int32(int32(yrDollar[3].i64)),
				XorMax: proto.Int32(int32(yrDollar[5].i64)),
			}
		}
	case 47:
		yrDollar = yrS[yrpt-0 : yrpt+1]
//line grammar.y:494
		{
			yrVAL.mod = &ast.StringModifiers{}
		}
	case 48:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line grammar.y:498
		{
			proto.Merge(yrDollar[1].mod, yrDollar[2].mod)
			yrVAL.mod = yrDollar[1].mod
		}
	case 49:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:506
		{
			yrVAL.mod = &ast.StringModifiers{Wide: proto.Bool(true)}
		}
	case 50:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:507
		{
			yrVAL.mod = &ast.StringModifiers{Ascii: proto.Bool(true)}
		}
	case 51:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:508
		{
			yrVAL.mod = &ast.StringModifiers{Nocase: proto.Bool(true)}
		}
	case 52:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:509
		{
			yrVAL.mod = &ast.StringModifiers{Fullword: proto.Bool(true)}
		}
	case 53:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:510
		{
			yrVAL.mod = &ast.StringModifiers{Private: proto.Bool(true)}
		}
	case 54:
		yrDollar = yrS[yrpt-0 : yrpt+1]
//line grammar.y:516
		{
			yrVAL.mod = &ast.StringModifiers{}
		}
	case 55:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line grammar.y:520
		{
			proto.Merge(yrDollar[1].mod, yrDollar[2].mod)
			yrVAL.mod = yrDollar[1].mod
		}
	case 56:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:528
		{
			yrVAL.mod = &ast.StringModifiers{Private: proto.Bool(true)}
		}
	case 57:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:534
		{
			yrVAL.id = &ast.Identifier{
				Items: []*ast.Identifier_IdentifierItem{
					{Item: &ast.Identifier_IdentifierItem_Identifier{yrDollar[1].s}},
				},
			}
		}
	case 58:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:542
		{
			yrVAL.id.Items = append(
				yrDollar[1].id.Items,
				&ast.Identifier_IdentifierItem{
					Item: &ast.Identifier_IdentifierItem_Identifier{yrDollar[3].s},
				},
			)
		}
	case 59:
		yrDollar = yrS[yrpt-4 : yrpt+1]
//line grammar.y:551
		{
			yrVAL.id.Items = append(
				yrDollar[1].id.Items,
				&ast.Identifier_IdentifierItem{
					Item: &ast.Identifier_IdentifierItem_Index{yrDollar[3].expr},
				},
			)
		}
	case 60:
		yrDollar = yrS[yrpt-4 : yrpt+1]
//line grammar.y:560
		{
			yrVAL.id.Items = append(
				yrDollar[1].id.Items,
				&ast.Identifier_IdentifierItem{
					Item: &ast.Identifier_IdentifierItem_Arguments{yrDollar[3].exprs},
				},
			)
		}
	case 61:
		yrDollar = yrS[yrpt-0 : yrpt+1]
//line grammar.y:572
		{
			yrVAL.exprs = &ast.Expressions{}
		}
	case 62:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:573
		{
			yrVAL.exprs = yrDollar[1].exprs
		}
	case 63:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:578
		{
			yrVAL.exprs = &ast.Expressions{
				Terms: []*ast.Expression{yrDollar[1].expr},
			}
		}
	case 64:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:584
		{
			yrVAL.exprs.Terms = append(yrDollar[1].exprs.Terms, yrDollar[3].expr)
		}
	case 65:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:592
		{
			regexp := yrDollar[1].reg
			yrVAL.regp = &regexp
		}
	case 66:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:600
		{
			yrVAL.expr = yrDollar[1].expr
		}
	case 67:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:605
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_BoolValue{true},
			}
		}
	case 68:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:611
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_BoolValue{false},
			}
		}
	case 69:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:617
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_BinaryExpression{
					BinaryExpression: &ast.BinaryExpression{
						Operator: ast.BinaryExpression_MATCHES.Enum(),
						Left:     yrDollar[1].expr,
						Right: &ast.Expression{
							Expression: &ast.Expression_Regexp{yrDollar[3].regp},
						},
					},
				},
			}
		}
	case 70:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:631
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_BinaryExpression{
					BinaryExpression: &ast.BinaryExpression{
						Operator: ast.BinaryExpression_CONTAINS.Enum(),
						Left:     yrDollar[1].expr,
						Right:    yrDollar[3].expr,
					},
				},
			}
		}
	case 71:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:643
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_StringIdentifier{yrDollar[1].s},
			}
		}
	case 72:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:649
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_BinaryExpression{
					BinaryExpression: &ast.BinaryExpression{
						Operator: ast.BinaryExpression_AT.Enum(),
						Left: &ast.Expression{
							Expression: &ast.Expression_StringIdentifier{yrDollar[1].s},
						},
						Right: yrDollar[3].expr,
					},
				},
			}
		}
	case 73:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:663
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_BinaryExpression{
					BinaryExpression: &ast.BinaryExpression{
						Operator: ast.BinaryExpression_IN.Enum(),
						Left: &ast.Expression{
							Expression: &ast.Expression_StringIdentifier{yrDollar[1].s},
						},
						Right: &ast.Expression{
							Expression: &ast.Expression_Range{yrDollar[3].rng},
						},
					},
				},
			}
		}
	case 74:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:678
		{
		}
	case 75:
		yrDollar = yrS[yrpt-9 : yrpt+1]
//line grammar.y:680
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_ForInExpression{
					ForInExpression: &ast.ForInExpression{
						ForExpression: yrDollar[2].forexp,
						Identifiers:   yrDollar[3].ss,
						Iterator:      yrDollar[5].iterator,
						Expression:    yrDollar[8].expr,
					},
				},
			}
		}
	case 76:
		yrDollar = yrS[yrpt-8 : yrpt+1]
//line grammar.y:693
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_ForOfExpression{
					ForOfExpression: &ast.ForOfExpression{
						ForExpression: yrDollar[2].forexp,
						StringSet:     yrDollar[4].strset,
						Expression:    yrDollar[7].expr,
					},
				},
			}
		}
	case 77:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:705
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_ForOfExpression{
					ForOfExpression: &ast.ForOfExpression{
						ForExpression: yrDollar[1].forexp,
						StringSet:     yrDollar[3].strset,
					},
				},
			}
		}
	case 78:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line grammar.y:716
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_NotExpression{yrDollar[2].expr},
			}
		}
	case 79:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:722
		{
			yrVAL.expr = createAndExpression(yrDollar[1].expr, yrDollar[3].expr)
		}
	case 80:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:726
		{
			yrVAL.expr = createOrExpression(yrDollar[1].expr, yrDollar[3].expr)
		}
	case 81:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:730
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_BinaryExpression{
					BinaryExpression: &ast.BinaryExpression{
						Operator: ast.BinaryExpression_LT.Enum(),
						Left:     yrDollar[1].expr,
						Right:    yrDollar[3].expr,
					},
				},
			}
		}
	case 82:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:742
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_BinaryExpression{
					BinaryExpression: &ast.BinaryExpression{
						Operator: ast.BinaryExpression_GT.Enum(),
						Left:     yrDollar[1].expr,
						Right:    yrDollar[3].expr,
					},
				},
			}
		}
	case 83:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:754
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_BinaryExpression{
					BinaryExpression: &ast.BinaryExpression{
						Operator: ast.BinaryExpression_LE.Enum(),
						Left:     yrDollar[1].expr,
						Right:    yrDollar[3].expr,
					},
				},
			}
		}
	case 84:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:766
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_BinaryExpression{
					BinaryExpression: &ast.BinaryExpression{
						Operator: ast.BinaryExpression_GE.Enum(),
						Left:     yrDollar[1].expr,
						Right:    yrDollar[3].expr,
					},
				},
			}
		}
	case 85:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:778
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_BinaryExpression{
					BinaryExpression: &ast.BinaryExpression{
						Operator: ast.BinaryExpression_EQ.Enum(),
						Left:     yrDollar[1].expr,
						Right:    yrDollar[3].expr,
					},
				},
			}
		}
	case 86:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:790
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_BinaryExpression{
					BinaryExpression: &ast.BinaryExpression{
						Operator: ast.BinaryExpression_NEQ.Enum(),
						Left:     yrDollar[1].expr,
						Right:    yrDollar[3].expr,
					},
				},
			}
		}
	case 87:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:802
		{
			yrVAL.expr = yrDollar[1].expr
		}
	case 88:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:806
		{
			yrVAL.expr = yrDollar[2].expr
		}
	case 89:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:814
		{
			yrVAL.intset = &ast.IntegerSet{
				Set: &ast.IntegerSet_IntegerEnumeration{yrDollar[2].intenum},
			}
		}
	case 90:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:820
		{
			yrVAL.intset = &ast.IntegerSet{
				Set: &ast.IntegerSet_Range{yrDollar[1].rng},
			}
		}
	case 91:
		yrDollar = yrS[yrpt-5 : yrpt+1]
//line grammar.y:830
		{
			yrVAL.rng = &ast.Range{
				Start: yrDollar[2].expr,
				End:   yrDollar[4].expr,
			}
		}
	case 92:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:841
		{
			yrVAL.intenum = &ast.IntegerEnumeration{
				Values: []*ast.Expression{yrDollar[1].expr},
			}
		}
	case 93:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:846
		{
			yrVAL.intenum.Values = append(yrVAL.intenum.Values, yrDollar[3].expr)
		}
	case 94:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:854
		{
			yrVAL.strset = &ast.StringSet{Set: &ast.StringSet_Strings{yrDollar[2].strenum}}
		}
	case 95:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:858
		{
			yrVAL.strset = &ast.StringSet{Set: &ast.StringSet_Keyword{ast.StringSetKeyword_THEM}}
		}
	case 96:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:866
		{
			yrVAL.strenum = &ast.StringEnumeration{
				Items: []*ast.StringEnumeration_StringEnumerationItem{yrDollar[1].strenumi},
			}
		}
	case 97:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:872
		{
			yrVAL.strenum.Items = append(yrDollar[1].strenum.Items, yrDollar[3].strenumi)
		}
	case 98:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:880
		{
			yrVAL.strenumi = &ast.StringEnumeration_StringEnumerationItem{
				StringIdentifier: proto.String(yrDollar[1].s),
				HasWildcard:      proto.Bool(false),
			}
		}
	case 99:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:887
		{
			yrVAL.strenumi = &ast.StringEnumeration_StringEnumerationItem{
				StringIdentifier: proto.String(yrDollar[1].s),
				HasWildcard:      proto.Bool(true),
			}
		}
	case 100:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:898
		{
			yrVAL.forexp = &ast.ForExpression{
				For: &ast.ForExpression_Expression{yrDollar[1].expr},
			}
		}
	case 101:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:904
		{
			yrVAL.forexp = &ast.ForExpression{
				For: &ast.ForExpression_Keyword{ast.ForKeyword_ALL},
			}
		}
	case 102:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:910
		{
			yrVAL.forexp = &ast.ForExpression{
				For: &ast.ForExpression_Keyword{ast.ForKeyword_ANY},
			}
		}
	case 103:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:920
		{
			yrVAL.ss = []string{yrDollar[1].s}
		}
	case 104:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:924
		{
			yrVAL.ss = append(yrDollar[1].ss, yrDollar[3].s)
		}
	case 105:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:931
		{
			yrVAL.iterator = &ast.Iterator{
				Iterator: &ast.Iterator_Identifier{yrDollar[1].id},
			}
		}
	case 106:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:937
		{
			yrVAL.iterator = &ast.Iterator{
				Iterator: &ast.Iterator_IntegerSet{yrDollar[1].intset},
			}
		}
	case 107:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:947
		{
			yrVAL.expr = yrDollar[2].expr
		}
	case 108:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:951
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_Keyword{ast.Keyword_FILESIZE},
			}
		}
	case 109:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:957
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_Keyword{ast.Keyword_ENTRYPOINT},
			}
		}
	case 110:
		yrDollar = yrS[yrpt-4 : yrpt+1]
//line grammar.y:963
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_IntegerFunction{
					&ast.IntegerFunction{
						Function: proto.String(yrDollar[1].s),
						Argument: yrDollar[3].expr,
					},
				},
			}
		}
	case 111:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:974
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_NumberValue{yrDollar[1].i64},
			}
		}
	case 112:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:980
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_DoubleValue{yrDollar[1].f64},
			}
		}
	case 113:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:986
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_Text{yrDollar[1].s},
			}
		}
	case 114:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:992
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_StringCount{yrDollar[1].s},
			}
		}
	case 115:
		yrDollar = yrS[yrpt-4 : yrpt+1]
//line grammar.y:998
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_StringOffset{
					&ast.StringOffset{
						StringIdentifier: proto.String(yrDollar[1].s),
						Index:            yrDollar[3].expr,
					},
				},
			}
		}
	case 116:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:1009
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_StringOffset{
					&ast.StringOffset{
						StringIdentifier: proto.String(yrDollar[1].s),
					},
				},
			}
		}
	case 117:
		yrDollar = yrS[yrpt-4 : yrpt+1]
//line grammar.y:1019
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_StringLength{
					&ast.StringLength{
						StringIdentifier: proto.String(yrDollar[1].s),
						Index:            yrDollar[3].expr,
					},
				},
			}
		}
	case 118:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:1030
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_StringLength{
					&ast.StringLength{
						StringIdentifier: proto.String(yrDollar[1].s),
					},
				},
			}
		}
	case 119:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:1040
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_Identifier{yrDollar[1].id},
			}
		}
	case 120:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line grammar.y:1046
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_UnaryExpression{
					&ast.UnaryExpression{
						Operator:   ast.UnaryExpression_UNARY_MINUS.Enum(),
						Expression: yrDollar[2].expr,
					},
				},
			}
		}
	case 121:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:1057
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_BinaryExpression{
					BinaryExpression: &ast.BinaryExpression{
						Operator: ast.BinaryExpression_PLUS.Enum(),
						Left:     yrDollar[1].expr,
						Right:    yrDollar[3].expr,
					},
				},
			}
		}
	case 122:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:1069
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_BinaryExpression{
					BinaryExpression: &ast.BinaryExpression{
						Operator: ast.BinaryExpression_MINUS.Enum(),
						Left:     yrDollar[1].expr,
						Right:    yrDollar[3].expr,
					},
				},
			}
		}
	case 123:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:1081
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_BinaryExpression{
					BinaryExpression: &ast.BinaryExpression{
						Operator: ast.BinaryExpression_TIMES.Enum(),
						Left:     yrDollar[1].expr,
						Right:    yrDollar[3].expr,
					},
				},
			}
		}
	case 124:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:1093
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_BinaryExpression{
					BinaryExpression: &ast.BinaryExpression{
						Operator: ast.BinaryExpression_DIV.Enum(),
						Left:     yrDollar[1].expr,
						Right:    yrDollar[3].expr,
					},
				},
			}
		}
	case 125:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:1105
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_BinaryExpression{
					BinaryExpression: &ast.BinaryExpression{
						Operator: ast.BinaryExpression_MOD.Enum(),
						Left:     yrDollar[1].expr,
						Right:    yrDollar[3].expr,
					},
				},
			}
		}
	case 126:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:1117
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_BinaryExpression{
					BinaryExpression: &ast.BinaryExpression{
						Operator: ast.BinaryExpression_XOR.Enum(),
						Left:     yrDollar[1].expr,
						Right:    yrDollar[3].expr,
					},
				},
			}
		}
	case 127:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:1129
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_BinaryExpression{
					BinaryExpression: &ast.BinaryExpression{
						Operator: ast.BinaryExpression_BITWISE_AND.Enum(),
						Left:     yrDollar[1].expr,
						Right:    yrDollar[3].expr,
					},
				},
			}
		}
	case 128:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:1141
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_BinaryExpression{
					BinaryExpression: &ast.BinaryExpression{
						Operator: ast.BinaryExpression_BITWISE_OR.Enum(),
						Left:     yrDollar[1].expr,
						Right:    yrDollar[3].expr,
					},
				},
			}
		}
	case 129:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line grammar.y:1153
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_UnaryExpression{
					UnaryExpression: &ast.UnaryExpression{
						Operator:   ast.UnaryExpression_BITWISE_NOT.Enum(),
						Expression: yrDollar[2].expr,
					},
				},
			}
		}
	case 130:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:1164
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_BinaryExpression{
					BinaryExpression: &ast.BinaryExpression{
						Operator: ast.BinaryExpression_SHIFT_LEFT.Enum(),
						Left:     yrDollar[1].expr,
						Right:    yrDollar[3].expr,
					},
				},
			}
		}
	case 131:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line grammar.y:1176
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_BinaryExpression{
					BinaryExpression: &ast.BinaryExpression{
						Operator: ast.BinaryExpression_SHIFT_RIGHT.Enum(),
						Left:     yrDollar[1].expr,
						Right:    yrDollar[3].expr,
					},
				},
			}
		}
	case 132:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line grammar.y:1188
		{
			yrVAL.expr = &ast.Expression{
				Expression: &ast.Expression_Regexp{yrDollar[1].regp},
			}
		}
	}
	goto yrstack /* stack new state and value */
}
